spring:
  datasource:
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    url: jdbc:${PROD_DB_URL}
    driver-class-name: ${PROD_DB_DRIVER_NAME}
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true # for postgresql
    hibernate:
      ddl-auto: update
    database-platform: ${PROD_DB_DIALECT_CLASS}

app:
  jwt:
    secret: ${PROD_JWT_SECRET}
    access-token:
      cookie-name: ${PROD_JWT_ACCESS_TOKEN_COOKIE_NAME}
      expiration-ms: ${PROD_JWT_ACCESS_TOKEN_EXPIRATION_MS}
    refresh-token:
        cookie-name: ${PROD_JWT_REFRESH_TOKEN_COOKIE_NAME}
        expiration-ms: ${PROD_JWT_REFRESH_TOKEN_EXPIRATION_MS}
  stripe:
    api: ${PROD_STRIPE_API}
    webhook:
        secret: ${PROD_STRIPE_WEBHOOK_SECRET}